name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for running secrets analysis within workflow
        id: checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: npm audit action
        uses: oke-py/npm-audit-action@v1.8.3
        with:
          # The value of `--audit-level` flag
          audit_level: low
          production_flag: false
          json_flag: false
          github_context: ${{ toJson(github) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: ostwindli,zoswing
          issue_labels: 'npm audit'
